app: taurus
component: scf
name: api
stage: dev
inputs:
  name: ${app}-${name}-${stage}
  src:
    src: ./src
  type: web
  runtime: Go1
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  triggers:
     - type: apigw
       name: SCF_API_DEV
       protocols:
        - http
        - https
       environment: test
       netTypes:
        - OUTER
       apis:
        - path: /
          method: ANY
