app: taurus
component: scf
name: api
stage: ${env:STAGE}
inputs:
  name: ${app}-${name}-${stage}
  src:
    src: ./src
  type: web
  runtime: Go1
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  # ignoreTriggers: true
  environment:
    variables: #  环境变量对象
      STAGE: ${stage}
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_NAME: ${env:DB_NAME}
      MULTIPLE: ${env:MULTIPLE}
      SMS_SDK_APP_ID: ${env:SMS_SDK_APP_ID}
      SMS_SIGN_NAME: ${env:SMS_SIGN_NAME}
      TEMPLATE_ID: ${env:TEMPLATE_ID}
      SECRET_ID: ${env:TENCENT_SECRET_ID}
      SECRET_KEY: ${env:TENCENT_SECRET_KEY}
  vpcConfig:
    vpcId: ${env:VPC_ID}
    subnetId: ${env:SUBNET_ID}
  events:
    - apigw:
        parameters:
          serviceName: ${env:API_GW_SERVICE_NAME}
          serviceId: ${env:API_GW_SERVICE_ID}
          protocols:
            - http
            - https
          netTypes:
            - OUTER
          environment: release
          endpoints:
            - path: /
              method: ANY
              enableCORS: true
              apiName: ${app}-${name}-${stage}
